apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/princekhanna13/argocd.git
    targetRevision: HEAD
    path: dev/charts
  destination: 
    server: https://kubernetes.default.svc
    namespace: argoexample

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
